eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

spring:
  application:
    name: product-view-service-feign-hystrix
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

# feign\u5F00\u542F\u7194\u65AD\u5668
feign:
  hystrix:
    enabled: true