eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: product-service-zuul
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8011

zuul:
  routes:
    # 以 /api/data/ 开头的请求都转发给 PRODUCT-DATA-SERVICE 服务
    api-a:
      path: /api/data/**
      serviceId: PRODUCT-DATA-SERVICE
    # 以 /api/view/ 开头的请求都转发给 PRODUCT-VIEW-SERVICE-FEIGN-HYSTRIX 服务
    api-b:
      path: /api/view/**
      serviceId: PRODUCT-VIEW-SERVICE-FEIGN-HYSTRIX
