eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      # git仓库分支
      label: master
      server:
        git:
          # Git 仓库地址（GitHub、GitLab、码云 ...）
          uri: https://github.com/xu1211/spring-cloud-config.git
          # 路径名
          searchPaths: respo
          username:
          password:
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8888

